### ISSUE TITLE
FireKit does not build with Carthage when "--no-use-binaries" option is specified.

### ISSUE THREAD

**Issue by stupergenius** [ryanbaldwin/FireKit#17]
When choosing to integrate FireKit with Carthage, and when specifying the `--no-use-binaries` option for Carthage, Carthage fails to build FireKit with an error like:

```
Carthage/Checkouts/FireKit/firekit/firekit/classes/models/Resource.swift:10:8: error: no such module 'RealmSwift'
import RealmSwift

Carthage/Checkouts/FireKit/firekit/firekit/classes/models/Resource.swift:10:8: error: no such module 'RealmSwift'
import RealmSwift

etc.
```

Produced with a simple `Cartfile` like:

```ruby
github "ryanbaldwin/FireKit" == 2.40.03
```

And by running:

```bash
carthage update --platform iOS --no-use-binaries --configuration Debug
```

However, when removing the `--no-use-binaries` option, Carthage downloads the FireKit binary and everything works fine.

It's my suspicion that, since FireKit only uses a private Cartfile (in `firekit/Cartfile.private`) to declare its dependencies, projects that need to build their dependencies from source do not know that FireKit actually requires Realm to compile. However, when Carthage prepares its own binary for publication, it's using the dependencies installed as specified by the private Cartfile.

As such, I believe it's necessary for at least the Realm dependency be declared in the public `Cartfile`, as in:

```ruby
github "realm/realm-cocoa" ~> 2.0
```

Where the above uses a "fuzzy" specifier intentionally to allow dependent projects to declare their own exact Realm version.

**Comment by ryanbaldwin** [comment]
Apologies for my tardiness - I just saw this now... I will check my filters in gmail and see what's catching my notifications. Thanks for logging this, and for the excellent detail. I see your PR so I'll take a look at that and respond. 

Cheers!

**Comment by ryanbaldwin** [comment]
This is super helpful, thanks for logging this Ben. I made a simple comment in PR #18 re: the `buddybuild_postclone.sh` file. If you can fix that up then we should be solid.

Thanks again!
